# Generated by Django 5.0.2 on 2024-02-25 08:41

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startup", "0002_contactmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmodel",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default=None, max_length=128, null=True, region="IN"
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("BC", "Basic"),
                            ("STD", "Standard"),
                            ("PNL", "Professional"),
                        ],
                        default="BC",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["category_type"],
                "indexes": [
                    models.Index(
                        fields=["category_type"], name="startup_cat_categor_2f2e82_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("point_1", models.CharField(blank=True, default=None, max_length=200)),
                ("point_2", models.CharField(blank=True, default=None, max_length=200)),
                ("point_3", models.CharField(blank=True, default=None, max_length=200)),
                ("point_4", models.CharField(blank=True, default=None, max_length=200)),
                ("point_5", models.CharField(blank=True, default=None, max_length=200)),
                ("point_6", models.CharField(blank=True, default=None, max_length=200)),
                ("point_7", models.CharField(blank=True, default=None, max_length=200)),
                ("point_8", models.CharField(blank=True, default=None, max_length=200)),
                ("point_9", models.CharField(blank=True, default=None, max_length=200)),
                (
                    "point_10",
                    models.CharField(blank=True, default=None, max_length=200),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="startup.category",
                    ),
                ),
            ],
            options={
                "ordering": ["category"],
                "indexes": [
                    models.Index(
                        fields=["id", "slug"], name="startup_pro_id_8e2ce3_idx"
                    ),
                    models.Index(
                        fields=["category"], name="startup_pro_categor_647a4a_idx"
                    ),
                    models.Index(
                        fields=["-created"], name="startup_pro_created_a0958e_idx"
                    ),
                ],
            },
        ),
    ]
