# Generated by Django 5.0.2 on 2024-02-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startup", "0003_alter_contactmodel_phone_number_category_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnouncementModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anouncement", models.CharField(max_length=200)),
            ],
        ),
    ]
