# Generated by Django 5.0.2 on 2024-03-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_checkoutmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutmodel',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutmodel',
            name='street_address',
            field=models.CharField(max_length=50),
        ),
    ]
